#!/usr/bin/perl -w

use Formalize2;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Formalize2",
   ReceiveHandler => \&Receive);
$UNIVERSAL::formalize2 = Formalize2->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::formalize2->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::formalize2->Execute();
